import './App.css';
import { Button } from './components/Button';

function App() {
  return (
    <>
      <div
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          flexDirection: 'column',
          margin: '0 0 0 150px',
        }}
        className="button-papa"
      >
        <div
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            margin: '50px 0 50px 0',
            flexDirection:"column",
          }}
        >
          <div className="outlined">
            <h1>OUTLINED</h1>
            <Button
              size="outlined"
              color="outlined"
              weight="outlined"
              padding="outlinedHover"
              backgroundColor='outlined'
              border='outlinedHover'
            >
              :HOVER
            </Button>
            <Button
              size="outlined"
              color="outlined"
              weight="outlined"
              padding="outlinedNormal"
              backgroundColor='outlined'
              border='outlinedNormal'
              marginLeft='left'
            >
              :NORMAL
            </Button>
            <Button
              size="outlined"
              color="active"
              weight="outlined"
              padding="outlinedActive"
              backgroundColor='activeOutlined'
              border='none'
              marginLeft='left'
            >
              :ACTIVE
            </Button>
            <Button
              size="outlined"
              color="disabled"
              weight="outlined"
              padding="outlinedDisabled"
              backgroundColor='outlined'
              border='outlinedDisabled'
              marginLeft='left'
            >
              :DISABLED
            </Button>
          </div>
          <div className="contained">
            <h1>CONTAINED</h1>
            <Button
              size="contained"
              color="contained"
              weight="contained"
              padding="containedHover"
              backgroundColor='containedHover'
              border='none'
            >
              :HOVER
            </Button>
            <Button
              size="contained"
              color="contained"
              weight="contained"
              padding="containedNormal"
              backgroundColor='containedNormal'
              border='none'
              marginLeft='left'
            >
              :NORMAL
            </Button>
            <Button
              size="contained"
              color="contained"
              weight="contained"
              padding="containedActive"
              backgroundColor='containedActive'
              border='none'
              marginLeft='left'
            >
              :ACTIVE
            </Button>
            <Button
              size="contained"
              color="contained"
              weight="contained"
              padding="containedDisabled"
              backgroundColor='containedDisabled'
              border='none'
              marginLeft='left'
            >
              :DISABLED
            </Button>
          </div>
        </div>
        <div style={{ display: 'flex', justifyContent: 'space-between',flexDirection:'column' }}>
          <div className="warning">
            <h1>WARNING</h1>
            <Button
              size="warning"
              color="warning"
              weight="warning"
              padding="warningHover"
              backgroundColor='warningHover'
              border='none'
            >
              :HOVER
            </Button>
            <Button
              size="warning"
              color="warning"
              weight="warning"
              padding="warningNormal"
              backgroundColor='warningNormal'
              border='none'
              marginLeft='left'
            >
              :NORMAL
            </Button>
            <Button
              size="warning"
              color="warning"
              weight="warning"
              padding="warningActive"
              backgroundColor='warningActive'
              border='none'
              marginLeft='left'
            >
              :ACTIVE
            </Button>
            <Button
              size="warning"
              color="warning"
              weight="warning"
              padding="warningDisabled"
              backgroundColor='warningDisabled'
              border='none'
              marginLeft='left'
            >
              :DISABLED
            </Button>
          </div>
          <div className="danger">
            <h1>DANGER</h1>
            <Button
              size="danger"
              color="danger"
              weight="danger"
              padding="dangerHover"
              backgroundColor='dangerHover'
              border='none'
            >
              :HOVER
            </Button>
            <Button
              size="danger"
              color="danger"
              weight="danger"
              padding="dangerNormal"
              backgroundColor='dangerNormal'
              border='none'
              marginLeft='left'
            >
              :NORMAL
            </Button>
            <Button
              size="danger"
              color="danger"
              weight="danger"
              padding="dangerActive"
              backgroundColor='dangerActive'
              border='none'
              marginLeft='left'
            >
              :ACTIVE
            </Button>
            <Button
              size="danger"
              color="danger"
              weight="danger"
              padding="dangerDisabled"
              backgroundColor='dangerDisabled'
              border='none'
              marginLeft='left'
            >
              :DISABLED
            </Button>
          </div>
        </div>
      </div>
    </>
  );
}

export default App;
